Program 1:

class MyException(Exception):
	def _init_(self,v):
               		 self.v=v
        def _str_(self):
                   	return str(self.v)
	def xyz(a,b):
                        c= a+b
                        if c < 150:
                      		raise MyException('custom exception occurred')
                      	else :
                        	return c
a=int(input())
b=int(input())
print(xyz(a,b))





Program 2:

try:
	n=int(input())
 	b=int(input())
 	a=input()
        c=n+b
        l=a+b
        n.append(3)
except ValueError:
            raise ValueError('value error occurred')
except TypeError:
             raise TypeError('Type error occurred')
except:
	raise AttributeError(' Attribute error occurred ')
  





Program 3:

while (1):
	try:
 		n=int(input())
        except:
       		print('error occurred')
